#!/usr/bin/python
import subprocess

from utils import get_zookeeper_servers

zk_servers = get_zookeeper_servers()
subprocess.check_output(
    ['relation-set', 'port=9092', 'zookeepers="%s"' % zk_servers])
