#!/bin/bash

set -ex
HOME=$PWD
. ${HOME}/hooks/common.sh

${HOME}/hooks/stop

juju-log "Do not forget to add a relation with a Kafka server for normal behavior"
juju-log "Configuration done. Moving to next stage"

${HOME}/hooks/start

exit 0
