#!/bin/sh

set -ex
HOME=$PWD
. ${HOME}/hooks/common.sh

juju-log "$JUJU_REMOTE_UNIT joined"

KAFKA_MEMBER_ADDRESS=`relation-get private-address $JUJU_REMOTE_UNIT`
KAFKA_MEMBER_PORT=`relation-get port $JUJU_REMOTE_UNIT`

if [ -z "${KAFKA_MEMBER_ADDRESS}"  ] || [ -z "${KAFKA_MEMBER_PORT}"  ] ; then
    exit 0
fi

MEMBERS=""
for MEMBER in `relation-list` ; do  
        juju-log "Adding $BROKER to configuration"
        MEMBER_HOST=`relation-get private-address ${MEMBER}`
        MEMBER_PORT=`relation-get port ${MEMBER}`
        MEMBERS="${MEMBERS},${MEMBER_HOST}:${MEMBER_PORT}"
done

MEMBERS=`echo ${MEMBERS} | sed s/^,//`

sed -i s/^rts\.spark\.khosts.*/rts\.spark\.khosts\:\ "${MEMBERS}"/ ${CONFIG_FILE}

${HOME}/hooks/config-changed

exit 0
